Activity03/Activity3/Models/CustomerModel.cs
/*
 * ---------------------------------------------------------------
 * Name      : Kelly Lamb
 * Date      : 2020-11-02
 * Class     : CST-247 Enterprise Computer Programming III
 * Professor : Dinesh Sthapit M.S.
 * Assignment: Activity 3 Multiple Sections
 * Disclaimer: This is my own work
 * ---------------------------------------------------------------
 * Description:
 * Part 1: Razor Forms, Partial Views (with and without Ajax)
 * Part 2: Utilize Visual Studio Debug features
 * ---------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Activity3.Models
{
    public class CustomerModel
    {
        public CustomerModel(int id, string name, int age)
        {
            ID = id;
            Name = name;
            Age = age;
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

Activity03/Activity3/Controllers/CustomerController.cs
/*
 * ---------------------------------------------------------------
 * Name      : Kelly Lamb
 * Date      : 2020-11-02
 * Class     : CST-247 Enterprise Computer Programming III
 * Professor : Dinesh Sthapit M.S.
 * Assignment: Activity 3 Multiple Sections
 * Disclaimer: This is my own work
 * ---------------------------------------------------------------
 * Description:
 * Part 1: Razor Forms, Partial Views (with and without Ajax)
 * Part 2: Utilize Visual Studio Debug features
 * ---------------------------------------------------------------
 */

using Activity3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Activity3.Controllers
{
    public class CustomerController : Controller
    {
        public CustomerModel customer;
        public List<CustomerModel> customers = new List<CustomerModel>();

        public CustomerController()
        {
            // Create list of new customers
            customers.Add(new CustomerModel(0, "Mickey Mouse", 55));
            customers.Add(new CustomerModel(1, "Minnie Mouse", 54));
            customers.Add(new CustomerModel(2, "Donald Duck", 53));
            customers.Add(new CustomerModel(3, "Daisy Duck", 52));
            customers.Add(new CustomerModel(4, "Clarabelle Cow", 26));
            customers.Add(new CustomerModel(5, "Oswald Rabbit", 58));
        }

        // GET: Customer
        public ActionResult Index()
        {
            Tuple<List<CustomerModel>, CustomerModel> tuple;
            tuple = new Tuple<List<CustomerModel>, CustomerModel>(customers, customers[0]);

            ViewBag.Title = "Ajax";
            return View("CustomerAjax", tuple);
        }

        [HttpPost]
        public ActionResult OnSelectCustomer(string Customer)
        {
            Tuple<List<CustomerModel>, CustomerModel> tuple;
            tuple = new Tuple<List<CustomerModel>, CustomerModel>(customers, customers[Int32.Parse(Customer)]);

            ViewBag.Title = "Ajax Partial";
            return PartialView("_CustomerDetails", customers[Int32.Parse(Customer)]);
        }

        [HttpPost]
        public ActionResult OnSelectCustomer1(string Customer)
        {
            Tuple<List<CustomerModel>, CustomerModel> tuple;
            tuple = new Tuple<List<CustomerModel>, CustomerModel>(customers, customers[Int32.Parse(Customer)]);

            ViewBag.Title = "No Ajax";
            return View("CustomerNoAjax", tuple);
        }

        [HttpPost]
        public string GetMoreInfo(string Customer)
        {
            return customers[Int32.Parse(Customer)].Name + " is a very well-known animated character by Walt Disney Studios";
        }
    }
}

Activity03/Activity3/Controllers/HomeController.cs
/*
 * ---------------------------------------------------------------
 * Name      : Kelly Lamb
 * Date      : 2020-11-02
 * Class     : CST-247 Enterprise Computer Programming III
 * Professor : Dinesh Sthapit M.S.
 * Assignment: Activity 3 Multiple Sections
 * Disclaimer: This is my own work
 * ---------------------------------------------------------------
 * Description:
 * Part 1: Razor Forms, Partial Views (with and without Ajax)
 * Part 2: Utilize Visual Studio Debug features
 * ---------------------------------------------------------------
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Activity3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Activity03/Activity3/Views/Customer/Customer.cshtml
@using Activity3.Models;

@model Tuple<List<CustomerModel>, CustomerModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Label("Please select a customer");
<br />

@using (Html.BeginForm("OnSelectCustomer", "Customer", FormMethod.Post, new { @id = "myform", @name = "myform" }))
{
    @Html.AntiForgeryToken();

    var selected = false;

    foreach (var customer in Model.Item1)
    {
        if (Model.Item2 == customer)
        {
            selected = true;
        }
        else
        {
            selected = false;
        }
        @Html.RadioButton("Customer", customer.ID, selected, new { onchange = "$('#myform').trigger('submit');" });
        @Html.Label(customer.Name);
        <br />
    }
}

<div id="customerInfo">

    @Html.Partial("~/Views/Shared/_CustomerDetails.cshtml", Model.Item2);
</div>

Activity03/Activity3/Views/Customer/CustomerAjax.cshtml
@using Activity3.Models;

@model Tuple<List<CustomerModel>, CustomerModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    AjaxOptions ajaxOptions = new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "customerInfo",
        OnSuccess = "ajaxSuccess"
    };
}

@Html.Label("Please select a customer");
<br />

@using (Ajax.BeginForm("OnSelectCustomer", "Customer", ajaxOptions, new { @id = "myform", @name = "myform" }))
{
    @Html.AntiForgeryToken();

    var selected = false;

    foreach (var customer in Model.Item1)
    {
        if (Model.Item2 == customer)
        {
            selected = true;
        }
        else
        {
            selected = false;
        }
        @Html.RadioButton("Customer", customer.ID, selected, new { onchange = "$('#myform').trigger('submit');" });
        @Html.Label(customer.Name);
        <br />
    }
}

<script type="text/javascript">
    function ajaxSuccess(data) {
        $.post('@Url.Action("GetMoreInfo", "Customer")', { customer: 2 }, function (data) { alert(data); });
     }
</script>

<div id="customerInfo">
    @Html.Partial("~/Views/Shared/_CustomerDetails.cshtml", Model.Item2)
</div>

Activity03/Activity3/Views/Customer/CustomerNoAjax.cshtml
@using Activity3.Models;

@model Tuple<List<CustomerModel>, CustomerModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Label("Please select a customer");
<br />

@using (Html.BeginForm("OnSelectCustomer1", "Customer", FormMethod.Post, new { @id = "myform", @name = "myform" }))
{
    @Html.AntiForgeryToken();

    var selected = false;

    foreach (var customer in Model.Item1)
    {
        if (Model.Item2 == customer)
        {
            selected = true;
        }
        else
        {
            selected = false;
        }
        @Html.RadioButton("Customer", customer.ID, selected, new { onchange = "$('#myform').trigger('submit');" } );
        @Html.Label(customer.Name);
        <br />
    }
}

<div id="customerInfo">

    @Html.Partial("~/Views/Shared/_CustomerDetails.cshtml", Model.Item2);
</div>